name: Minimal Build Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  minimal-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install minimal deps
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libssl-dev
    
    - name: Find nlohmann-json
      run: |
        # Try to find or install nlohmann-json
        if ! pkg-config --exists nlohmann_json; then
          echo "Installing nlohmann-json from apt"
          sudo apt-get install -y nlohmann-json3-dev
        fi
    
    - name: Configure minimal
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF \
                 -DCMAKE_CXX_STANDARD=17 \
                 -DCMAKE_BUILD_TYPE=Release
    
    - name: Build library
      run: |
        cd build
        make neocpp VERBOSE=1
    
    - name: Verify library
      run: |
        ls -la build/libneocpp.a
        file build/libneocpp.a