name: Build Without CURL

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-no-curl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install minimal dependencies (no CURL)
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libssl-dev nlohmann-json3-dev
    
    - name: Configure without CURL
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TESTS=OFF \
                 -DBUILD_EXAMPLES=OFF \
                 -DCMAKE_BUILD_TYPE=Release
        echo "=== CMake Cache CURL status ==="
        grep -i curl CMakeCache.txt || echo "No CURL references"
    
    - name: Build library
      run: |
        cd build
        echo "=== Object files before build ==="
        find . -name "*.o" | wc -l
        
        echo "=== Running make ==="
        make VERBOSE=1 2>&1 | tee build.log
        
        echo "=== Object files after build ==="
        find . -name "*.o" | wc -l
        
        echo "=== Looking for library files ==="
        find . -name "*.a" -ls
        
        echo "=== Build directory contents ==="
        ls -la
    
    - name: Check if library exists
      run: |
        if [ -f build/libneocpp.a ]; then
          echo "SUCCESS: Library created!"
          ls -la build/libneocpp.a
        else
          echo "FAILURE: Library not created"
          echo "=== Checking for build errors ==="
          grep -i "error" build/build.log || echo "No errors found"
          exit 1
        fi