name: Quick Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  quick-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install minimal dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libssl-dev libcurl4-openssl-dev nlohmann-json3-dev
    
    - name: Configure with verbose output
      run: |
        cmake -S . -B build -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF || (echo "CMake failed"; cat CMakeFiles/CMakeError.log; exit 1)
    
    - name: Build library only
      run: |
        cmake --build build --target neocpp --verbose || (echo "Build failed"; exit 1)
    
    - name: Check library
      run: |
        ls -la build/
        file build/libneocpp.a || echo "Library not found"