name: Simple Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  simple-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libssl-dev nlohmann-json3-dev
    
    - name: Build with simple make
      run: |
        echo "=== Creating build directory ==="
        mkdir -p build
        cd build
        
        echo "=== Configuring with CMake ==="
        cmake .. -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF
        
        echo "=== Building with make (default target) ==="
        make VERBOSE=1
        
        echo "=== Checking for library ==="
        ls -la lib* || echo "No libraries found"
        
        echo "=== Checking entire build directory ==="
        find . -type f -name "*.a" -o -name "*.so"
    
    - name: Alternative build approach
      if: failure()
      run: |
        echo "=== Trying alternative build ==="
        rm -rf build
        mkdir build && cd build
        cmake .. -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=Debug
        cmake --build . --verbose
        find . -name "*.a"